apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-mjmx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-devfile-sample-hello-world-mjmx
    app.kubernetes.io/part-of: test-app-odmf
  name: docker-devfile-sample-hello-world-mjmx
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-devfile-sample-hello-world-mjmx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: docker-devfile-sample-hello-world-mjmx
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-zwsb-tenant/test-app-odmf/docker-devfile-sample-hello-world-mjmx@sha256:0b21c536c26c4bafb7023987f7e146cc99230d017ddc399cf724882d070bd6d3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
